### ISSUE TITLE
Visible solution on a running code challenge

### ISSUE THREAD

**Issue by rubenkindt** [benfidlers/AoC#1]
Hi, can you make your solution visible 24 hours after that day's publication?

**Comment by bfidlers** [comment]
I don't really think it's a problem since there are tons of solutions online, but from no on I'll wait a day to post my solutions.

**Comment by bfidlers** [comment]
Changed my mind, I think it's beneficiary to put your code online. The spirit of the game is to enjoy yourself and to learn from each other, sometimes you are stuck and you could use some help, or you want to compare your solution with the solution of someone else. Postponing it a day doesn't help then, because you are already busy with a new puzzle. And if you don't want to see other solutions, than you just shouldn't look for them. Hope you understand!

**Comment by rubenkindt** [comment]
Yes i agree, I was not aware that others posted their solution online too, you even convinced me to turn mine public as well.
